"""Where uploaded site media lives. LocalStorage writes under MEDIA_DIR; an S3-compatible
backend can implement the same three methods and be selected with STORAGE_BACKEND."""

import re
from pathlib import Path
from typing import Protocol

from app.config import get_settings

# Keys are generated by the server (e.g. "visits/12/3f9c...e1.jpg"), never taken from uploads.
# Every segment starts with a letter or digit, so ".." and absolute paths cannot match.
_KEY = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.\-]*(/[A-Za-z0-9][A-Za-z0-9_.\-]*)*$")


class StorageKeyError(ValueError):
    pass


class Storage(Protocol):
    def save(self, key: str, data: bytes) -> None: ...
    def open(self, key: str) -> bytes: ...
    def delete(self, key: str) -> None: ...


class LocalStorage:
    def __init__(self, root: str | Path):
        self.root = Path(root).resolve()

    def _path(self, key: str) -> Path:
        if not _KEY.fullmatch(key or ""):
            raise StorageKeyError(f"Invalid storage key: {key!r}")
        path = (self.root / key).resolve()
        if self.root not in path.parents:
            raise StorageKeyError(f"Storage key escapes the media directory: {key!r}")
        return path

    def save(self, key: str, data: bytes) -> None:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)

    def open(self, key: str) -> bytes:
        return self._path(key).read_bytes()

    def delete(self, key: str) -> None:
        self._path(key).unlink(missing_ok=True)


def get_storage() -> Storage:
    settings = get_settings()
    if settings.storage_backend == "local":
        return LocalStorage(settings.media_dir)
    raise ValueError(f"Unknown STORAGE_BACKEND: {settings.storage_backend!r}")
