"""problems

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-27 21:43:43.665072

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, Sequence[str], None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "problems",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("site_visit_id", sa.Integer(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("problem", sa.String(length=300), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("location", sa.String(length=300), nullable=False),
        sa.Column("responsible_party", sa.String(length=200), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column(
            "status", sa.Enum("open", "resolved", name="problemstatus", native_enum=False, length=32), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by_id", sa.Integer(), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["site_visit_id"],
            ["site_visits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("problems", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_problems_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_problems_site_visit_id"), ["site_visit_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_problems_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("problems", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_problems_status"))
        batch_op.drop_index(batch_op.f("ix_problems_site_visit_id"))
        batch_op.drop_index(batch_op.f("ix_problems_project_id"))

    op.drop_table("problems")
    # ### end Alembic commands ###
