"""red flags and system audit events

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-27 22:14:53.226349

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: Union[str, Sequence[str], None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "red_flags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("rule", sa.String(length=40), nullable=False),
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("raised_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cleared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("clear_kind", sa.String(length=10), nullable=True),
        sa.Column("cleared_by_id", sa.Integer(), nullable=True),
        sa.Column("clear_reason", sa.Text(), nullable=True),
        sa.Column("condition_ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["cleared_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("red_flags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_red_flags_cleared_at"), ["cleared_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_red_flags_project_id"), ["project_id"], unique=False)

    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.alter_column("actor_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.alter_column("actor_id", existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table("red_flags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_red_flags_project_id"))
        batch_op.drop_index(batch_op.f("ix_red_flags_cleared_at"))

    op.drop_table("red_flags")
    # ### end Alembic commands ###
