"""project stages: the 18-stage flow per project, with v2 projects backfilled as onboarded mid-way.

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-27 23:36:19.205427

"""
from typing import Sequence, Union

from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('locked', 'active', 'completed', 'historical', name='stagestatus', native_enum=False, length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('completion_note', sa.Text(), nullable=True),
    sa.Column('historical_confirmed_by', sa.String(length=120), nullable=True),
    sa.Column('historical_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'key')
    )
    with op.batch_alter_table('project_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_stages_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###
    _backfill()


# Frozen copy of the stage order at this revision (stage_config.STAGES). Migrations never import app code.
_KEYS = ["setup", "discovery", "baseline", "requirements_signoff", "predesign_site_visit", "investigations",
         "concept", "tentative_elevations", "grid", "grid_freeze", "structural_design", "architectural_package",
         "structural_package", "mep", "elevations_package", "design_freeze_signoff", "payment_gate",
         "detailed_drawings", "line_out", "construction", "civil_completion", "interiors_signoff", "handover_signoff"]


def _backfill() -> None:
    """Projects from sprint v2 were running the construction loop, so they join the tracker at Site line-out:
    earlier stages become historical, line-out is done once visits exist, and construction is then open."""
    bind = op.get_bind()
    now = datetime.now(timezone.utc)
    stages = sa.table("project_stages", sa.column("project_id"), sa.column("key"), sa.column("status"),
                      sa.column("started_at"), sa.column("completed_at"), sa.column("historical_confirmed_by"),
                      sa.column("historical_note"))
    projects = bind.execute(sa.text("select id from projects")).scalars().all()
    for pid in projects:
        has_visits = bind.execute(sa.text("select count(*) from site_visits where project_id = :p and status != 'draft'"),
                                  {"p": pid}).scalar() > 0
        rows = []
        for key in _KEYS:
            row = {"project_id": pid, "key": key, "status": "locked", "started_at": None, "completed_at": None,
                   "historical_confirmed_by": None, "historical_note": None}
            if _KEYS.index(key) < _KEYS.index("line_out"):
                row.update(status="historical", historical_confirmed_by="SiteFlow v2 migration",
                           historical_note="Completed before SiteFlow tracked project stages.")
            elif key == "line_out":
                row.update(status="completed" if has_visits else "active", started_at=now,
                           completed_at=now if has_visits else None)
            elif key == "construction" and has_visits:
                row.update(status="active", started_at=now)
            rows.append(row)
        op.bulk_insert(stages, rows)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_stages_project_id'))

    op.drop_table('project_stages')
    # ### end Alembic commands ###
