"""signoffs

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-28 00:31:47.019855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, Sequence[str], None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signoff_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('stage_key', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'approved', 'changes_requested', name='signoffstatus', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_comment', sa.Text(), nullable=True),
    sa.Column('signer_id', sa.Integer(), nullable=True),
    sa.Column('signer_name', sa.String(length=120), nullable=True),
    sa.Column('method', sa.String(length=30), nullable=True),
    sa.Column('confirmation_text', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['signer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['signoff_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'stage_key', 'version')
    )
    with op.batch_alter_table('signoff_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signoff_requests_project_id'), ['project_id'], unique=False)

    op.create_table('signoff_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=120), nullable=False),
    sa.Column('content_type', sa.String(length=60), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=200), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['signoff_requests.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('signoff_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signoff_attachments_request_id'), ['request_id'], unique=False)

    op.create_table('signoff_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['signoff_attachments.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['signoff_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signoff_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signoff_views_request_id'), ['request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signoff_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signoff_views_request_id'))

    op.drop_table('signoff_views')
    with op.batch_alter_table('signoff_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signoff_attachments_request_id'))

    op.drop_table('signoff_attachments')
    with op.batch_alter_table('signoff_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signoff_requests_project_id'))

    op.drop_table('signoff_requests')
    # ### end Alembic commands ###
