"""shared updates

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-28 01:42:40.739401

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0009"
down_revision: Union[str, Sequence[str], None] = "0008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shared_updates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("site_visit_id", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("shared_by_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["shared_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["site_visit_id"],
            ["site_visits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("shared_updates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_shared_updates_project_id"), ["project_id"], unique=False)

    op.create_table(
        "shared_update_photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("update_id", sa.Integer(), nullable=False),
        sa.Column("media_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media.id"],
        ),
        sa.ForeignKeyConstraint(
            ["update_id"],
            ["shared_updates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("update_id", "media_id"),
    )
    with op.batch_alter_table("shared_update_photos", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_shared_update_photos_update_id"), ["update_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shared_update_photos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shared_update_photos_update_id"))

    op.drop_table("shared_update_photos")
    with op.batch_alter_table("shared_updates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shared_updates_project_id"))

    op.drop_table("shared_updates")
    # ### end Alembic commands ###
