"""stage exceptions

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-28 05:39:37.322760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0011'
down_revision: Union[str, Sequence[str], None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stage_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('stage_key', sa.String(length=40), nullable=False),
    sa.Column('gate', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'stage_key', 'gate')
    )
    with op.batch_alter_table('stage_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stage_exceptions_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stage_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stage_exceptions_project_id'))

    op.drop_table('stage_exceptions')
    # ### end Alembic commands ###
