"""fee plan

Revision ID: 0013
Revises: 0012
Create Date: 2026-09-28 06:19:59.853902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0013'
down_revision: Union[str, Sequence[str], None] = '0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_value', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False))
        batch_op.add_column(sa.Column('fee_basis', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('fee_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('fee_notes')
        batch_op.drop_column('fee_basis')
        batch_op.drop_column('currency')
        batch_op.drop_column('contract_value')

    # ### end Alembic commands ###
