"""project image

Revision ID: 0017
Revises: 0016
Create Date: 2026-09-28 09:47:25.152429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0017'
down_revision: Union[str, Sequence[str], None] = '0016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_key', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('image_thumb_key', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('image_content_type', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('image_sha256', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('image_updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('image_updated_at')
        batch_op.drop_column('image_sha256')
        batch_op.drop_column('image_content_type')
        batch_op.drop_column('image_thumb_key')
        batch_op.drop_column('image_key')

    # ### end Alembic commands ###
