"""approval delegations

Revision ID: 0021
Revises: 0020
Create Date: 2026-09-28 11:13:11.639895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0021'
down_revision: Union[str, Sequence[str], None] = '0020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_delegations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('delegator_id', sa.Integer(), nullable=False),
    sa.Column('delegate_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delegate_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delegator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_delegations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_delegations_delegate_id'), ['delegate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_delegations_delegator_id'), ['delegator_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_delegations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_delegations_delegator_id'))
        batch_op.drop_index(batch_op.f('ix_approval_delegations_delegate_id'))

    op.drop_table('approval_delegations')
    # ### end Alembic commands ###
